spring:
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc

  jpa:
    database: h2
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        query:
          plan_cache_max_size: 512
          plan_parameter_metadata_max_size: 64
          in_clause_parameter_padding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
